language: rust

rust:
  - nightly

branches:
  only:
  - main

matrix:
  include:
    - os: linux
      rust: nightly

before_install:
  - sudo apt-get update
  - sudo apt-get -y install rrdtool openssh-server
  - sudo ssh-keygen -A -f /
  - ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa <<<y 2>&1 >/dev/null
  - cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys
  - sudo /etc/init.d/ssh start
  - ssh-keyscan -H localhost >> ~/.ssh/known_hosts
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

script:
  - export CARGO_INCREMENTAL=0
  - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
  - export RUSTDOCFLAGS="-Cpanic=abort"
  - cargo build --verbose $CARGO_OPTIONS
  - RUST_LOG=trace cargo test --verbose $CARGO_OPTIONS -- --nocapture
  - |
    zip -0 ccov.zip `find . \( -name "cgg*.gc*" \) -print`;
    ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --excl-start "#\[cfg\(test\)\]" --excl-br-start "#\[cfg\(test\)\]" --excl-line "#\[derive\(" --excl-br-line "#\[derive\(" -o lcov.info;
    bash <(curl -s https://codecov.io/bash) -f lcov.info;
